### ISSUE TITLE
Request: Colour entire message

### ISSUE THREAD

**Issue by filliph** [BelegCufea/PrettyReputation#6] opened 2023-03-21 23:14 UTC
I'm basically using this add-on as a lightweight version of [Reputation Guide](https://www.curseforge.com/wow/addons/reputation-guide) as my UI hides 99% of functionality in that add-on.

I've configured PrettyReputation to print a message like this:
```
Reputation with Iskaara Tuskarr increased by +100. (Total: +100, Left: 4987) 
```
Would it be possible to offer an option to colour the entire message using Blizzard's default reputation text colour?

Yes I'm old and resistant to change so I want to replicate the old functionality 😂

**Comment by BelegCufea** [comment] 2023-03-22 04:44
I have been thinking about including the TAG `[standingColor]` that would do exactly this.

The issue is that Blizzard requires a closing escape code "|r" for color definition "|cAARRGGBB". I could rewrite the TAG engine, or do you think it would be too much of a hassle to include some kind of TAG that will "close" the color change, like `[standingColorEnd]`? The starting TAG would then be `[standingColorStart]`.

The pattern for your message would read something like this:
```
[standingColorStart]Reputation with [c_name] [signText] by [change]. (Total: [session], Left: [toGo])[standingColorEnd]
```
I will also have to make the TAG signText for "increased" and "decreased" as well :-) :-)

Thanks for a suggestion.

**Comment by BelegCufea** [comment] 2023-03-22 05:54
I have just committed the above changes to  `master`.

If you are fine with my proposed idea of two enclosing TAGs, then it should be ready. This change should also fix the [Blizzard color scheme issue](https://github.com/BelegCufea/PrettyReputation/issues/5).

I have even added a group of TAGs called [standingNext]. They are not as versatile as the ones in the [Reputation Guide](https://www.curseforge.com/wow/addons/reputation-guide) addon, as they only work for normal progression, renown, and paragon factions. Additionally, I haven't yet coded in conditional text like "[{by }standingNext]" that will display the text in {} only if the TAG returns something. Nonetheless, they may still be useful. :-)

If you are willing to try it, it would be marvelous. Thank you in advance, and have a nice day.

**Comment by filliph** [comment] 2023-03-22 12:28
I'll try it out after work today, thank you for the speedy turn-around 😄 

> The issue is that Blizzard requires a closing escape code "|r" for color definition "|cAARRGGBB". I could rewrite the TAG engine, or do you think it would be too much of a hassle to include some kind of TAG that will "close" the color change, like `[standingColorEnd]`? The starting TAG would then be `[standingColorStart]`.

I think that's totally fine, this is entirely optional only for people who want their rep messages to stand out more from the normal addon messages that are all white 😄

**Comment by BelegCufea** [comment] 2023-03-22 16:44
Okay, I have been coding a bit and added optional prefixes and suffixes so that the message could be as close to the one generated by the [Reputation Guide](https://www.curseforge.com/wow/addons/reputation-guide):
```
Reputation with Iskaara Tuskarr increased by +100. (Total: +100, Left to Renown29: 4987)
```
The pattern for that message should be something like this:
```
[standingColorStart]Reputation with [c_name] [signText] by [change]. (Total: [session], Left[{ to }[standingNext]: [toGo])[standingColorEnd]
```
It will ignore the `[{ to }[standingNext]` if it can't find the next reputation rank (for all those Chromies and Cobalt Assemblies).

Code is commited to `master` and if it passes your tests, I will then release it as a beta on Curse.

Thank you very much for your help.

**Comment by filliph** [comment] 2023-03-22 17:24
Will test in ~2 hours and get back to you, thank you 😄

**Comment by BelegCufea** [comment] 2023-03-22 17:37
No hurry, it seems we are in completely opposite time zones.

**Comment by filliph** [comment] 2023-03-22 18:55
The colour works, but there might have been a copy/paste error with the tags because the output in chat was:
```
[06:53:59 PM] Reputation with Dragonscale Expedition increased by +220. (Total: +330, Left[{ to }[standingNext]: 6213) 
```

Should it be 
```
[standingColorStart]Reputation with [c_name] [signText] by [change]. (Total: [session], Left[{ to }[standingNext]]: [toGo])[standingColorEnd]
```
instead?

**Comment by filliph** [comment] 2023-03-22 19:23
Nope, that doesn't seem to be it either. I tried both with `[{ to }[standingNext]]` and `{ to }[standingNext]` and neither works for me.

**Comment by BelegCufea** [comment] 2023-03-22 19:24
Yep. There is an error. I just wrote it in the chat withour trying it. It should be: 
```
[standingColorStart]Reputation with [c_name] [signText] by [change]. (Total: [session], Left[{ to }standingNext]: [toGo])[standingColorEnd]
```

`[{ to }standingNext]` insted of `[{ to }[standingNext]` (the open bracket before standingNext should not be there :-)

**Comment by filliph** [comment] 2023-03-22 19:27
```
[07:26:43 PM] Reputation with Valdrakken Accord increased by +28. (Total: +28, Left to Paragon 2: 4137) 
```
Works, thank you!

I can go kill some stuff in Cobalt Assembly until I get a rep drop to see if it works there too 🙂

**Comment by filliph** [comment] 2023-03-22 19:32
```
[07:31:37 PM] Reputation with Cobalt Assembly increased by +21. (Total: +21, Left: 1967)
```
Works, thank you!

**Comment by BelegCufea** [comment] 2023-03-22 20:32
Nice! I will post a new beta on curse. As fast as I kill all the rares on the new island :-)

**Closed as completed** 2023-03-22 21:50 UTC
Labels: enhancement
